version: '3'
services:
  server:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/src
      - .cache:/root/.npm
    working_dir: /src
    command: /bin/sh -c 'dos2unix start.sh && ./start.sh'
